# Use this playbook when building locally.

site:
  title: CAWG Organizational Identity Profile
  start_page: organizational-identity-profile::index.adoc

content:
  sources: 
  - url: .
    branches: HEAD
    start_path: docs

ui:
  bundle:
    url: https://cawg.io/antora-ui/ui-bundle.zip
    snapshot: true
  supplemental_files: ./custom-ui/

antora:
  extensions:
    - require: '@sntke/antora-mermaid-extension'
      mermaid_initialize_options:
        theme_variables:
          font_family: Roboto,sans-serif
